stages:
  prepare:
    desc: Sanitize the dataset
    cmd: python src\preprocess.py
    deps:
    - dataset\features.csv
    - src\preprocess.py
    outs:
    - dataset\test.csv
    - dataset\train.csv
    - dataset\val.csv
